name: Build and deploy Docker container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Setup Node.js

      - run: npm install
        name: Install dependencies

      - run: npm run build
        name: Verify ability to build

      - name: Build Docker Image
        run: docker build -t inversity-hackathon .

      - name: Save Docker Image as Tar
        run: docker save inversity-hackathon:latest -o inversity-hackathon.tar

      - name: Copy Docker Image to AWS Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "inversity-hackathon.tar"
          target: "/home/${{ secrets.AWS_USER }}/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into AWS and Load Image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo docker stop inversity-hackathon || true
            sudo docker rm inversity-hackathon || true
            sudo docker load -i /home/${{ secrets.AWS_USER }}/inversity-hackathon.tar
            sudo docker run -d -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} -p 3000:3000 -p 80:5174 --name inversity-hackathon inversity-hackathon
